### ISSUE TITLE
Google Analytics Report keeps loading

### ISSUE THREAD

**Issue by fl0-at** [silverstripe-archive/silverstripe-googleanalytics#36]
I have come across an issue with the GA Report in the admin panel - the page displays

> {Google Analytics}
> 
> Show:
> 
> loading...
> 
> Choose metrics to display

but it does not let me choose metrics to display or anything.

It works fine when I log in to my GA account and the tracking seems to work perfectly fine.
Is there a fix for this issue?

**Comment by Taitava** [comment]
The problem is that the Google API has changed (actually a long time ago) and it does not allow applications to log in using email address and password anymore.

The unclecheese/silverstripe-dashboard module has a working Google Analytics feature (among a few other features). Perhaps that could be used as an example when fixing this module. I would try to do it, but unfortunately I don't have time.
